modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
issueTrackerURL="https://github.com/willatendo/Tyrannotitan-Library/issues"

[[mods]]
modId="tyrannotitanlib"
version="3.0.1"
displayName="Tyrannotitan Library"
updateJSONURL="https://github.com/willatendo/Tyrannotitan-Library/raw/main/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tyrannotitan-library-forge"
logoFile="tyrannotitanlib.png"
credit="Gecko, Eliot, AzureDoom (GeckoLib : Tyrannomation) || Team Abnormals (Abnormals Core : Base) || Slime Knights (Mantle & Tinker's Construct : Tyrannobook) || Vazkii (AutoRegLib : Tyrannoregister)"
authors="Willatendo, Santispik3" 

description='''
A library for Willatendo's mods with tonnes of useful code including setup registers, base classes, compatablilty classes, mod books, and easy-to-use animations.

PLEASE NOTE: A LOT OF THE CODE IS FROM OTHER'S MODS. I IN NO WAY CLAM THIS CODE AS MY OWN!
'''

[[dependencies.tyrannotitanlib]]
    modId="forge" 
    mandatory=true 
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tyrannotitanlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
	