modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/willatendo/Tyrannotitan-Library/issues"

[[mods]]
modId="tyrannotitanlib"
version="v1.0.3"
displayName="Tyrannotitan Library"
updateJSONURL="https://github.com/willatendo/Tyrannotitan-Library/raw/main/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tyrannotitan-library-forge"
logoFile="tyrannotitanlib.png"
credit="Gecko, Eliot, AzureDoom (GeckoLib) || Team Abnormals (Various)"
authors="Willatendo, Santispik3"

description='''
A library full of utilities for mods!
'''

[[dependencies.tyrannotitanlib]]
    modId="forge" 
    mandatory=true 
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tyrannotitanlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
	